---
- name: Enable to install nginx
  shell: 'amazon-linux-extras enable nginx1.12'
  tags: nginx

- name: Install yum nginx
  yum:
    name: nginx
    state: installed
    lock_timeout: 180
  tags: nginx
